/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WsSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLWsSideDrawerElement extends Components.WsSideDrawer, HTMLStencilElement {
    }
    var HTMLWsSideDrawerElement: {
        prototype: HTMLWsSideDrawerElement;
        new (): HTMLWsSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "ws-side-drawer": HTMLWsSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface WsSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "ws-side-drawer": WsSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ws-side-drawer": LocalJSX.WsSideDrawer & JSXBase.HTMLAttributes<HTMLWsSideDrawerElement>;
        }
    }
}
