/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WsSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface WsTopDrawer {
        "menuLink": any[];
        "menuTitle": string;
        "open": () => Promise<void>;
        "opened": boolean;
    }
    interface WsWonkyDonkey {
        "menuLink": any[];
        "menuTitle": string;
        "opened": boolean;
    }
}
declare global {
    interface HTMLWsSideDrawerElement extends Components.WsSideDrawer, HTMLStencilElement {
    }
    var HTMLWsSideDrawerElement: {
        prototype: HTMLWsSideDrawerElement;
        new (): HTMLWsSideDrawerElement;
    };
    interface HTMLWsTopDrawerElement extends Components.WsTopDrawer, HTMLStencilElement {
    }
    var HTMLWsTopDrawerElement: {
        prototype: HTMLWsTopDrawerElement;
        new (): HTMLWsTopDrawerElement;
    };
    interface HTMLWsWonkyDonkeyElement extends Components.WsWonkyDonkey, HTMLStencilElement {
    }
    var HTMLWsWonkyDonkeyElement: {
        prototype: HTMLWsWonkyDonkeyElement;
        new (): HTMLWsWonkyDonkeyElement;
    };
    interface HTMLElementTagNameMap {
        "ws-side-drawer": HTMLWsSideDrawerElement;
        "ws-top-drawer": HTMLWsTopDrawerElement;
        "ws-wonky-donkey": HTMLWsWonkyDonkeyElement;
    }
}
declare namespace LocalJSX {
    interface WsSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface WsTopDrawer {
        "menuLink"?: any[];
        "menuTitle"?: string;
        "opened"?: boolean;
    }
    interface WsWonkyDonkey {
        "menuLink"?: any[];
        "menuTitle"?: string;
        "opened"?: boolean;
    }
    interface IntrinsicElements {
        "ws-side-drawer": WsSideDrawer;
        "ws-top-drawer": WsTopDrawer;
        "ws-wonky-donkey": WsWonkyDonkey;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ws-side-drawer": LocalJSX.WsSideDrawer & JSXBase.HTMLAttributes<HTMLWsSideDrawerElement>;
            "ws-top-drawer": LocalJSX.WsTopDrawer & JSXBase.HTMLAttributes<HTMLWsTopDrawerElement>;
            "ws-wonky-donkey": LocalJSX.WsWonkyDonkey & JSXBase.HTMLAttributes<HTMLWsWonkyDonkeyElement>;
        }
    }
}
