/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WsFullCover {
        "menuLink": any[];
        "opened": boolean;
    }
    interface WsHexMenu {
        "menuLink": any[];
        "opened": boolean;
    }
    interface WsSideButtons {
        "menuLink": any[];
    }
    interface WsSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "titl": string;
    }
    interface WsTopDrawer {
        "menuLink": any[];
        "menuTitle": string;
        "open": () => Promise<void>;
        "opened": boolean;
    }
    interface WsWonkyDonkey {
        "menuLink": any[];
        "menuTitle": string;
        "opened": boolean;
    }
}
declare global {
    interface HTMLWsFullCoverElement extends Components.WsFullCover, HTMLStencilElement {
    }
    var HTMLWsFullCoverElement: {
        prototype: HTMLWsFullCoverElement;
        new (): HTMLWsFullCoverElement;
    };
    interface HTMLWsHexMenuElement extends Components.WsHexMenu, HTMLStencilElement {
    }
    var HTMLWsHexMenuElement: {
        prototype: HTMLWsHexMenuElement;
        new (): HTMLWsHexMenuElement;
    };
    interface HTMLWsSideButtonsElement extends Components.WsSideButtons, HTMLStencilElement {
    }
    var HTMLWsSideButtonsElement: {
        prototype: HTMLWsSideButtonsElement;
        new (): HTMLWsSideButtonsElement;
    };
    interface HTMLWsSideDrawerElement extends Components.WsSideDrawer, HTMLStencilElement {
    }
    var HTMLWsSideDrawerElement: {
        prototype: HTMLWsSideDrawerElement;
        new (): HTMLWsSideDrawerElement;
    };
    interface HTMLWsTopDrawerElement extends Components.WsTopDrawer, HTMLStencilElement {
    }
    var HTMLWsTopDrawerElement: {
        prototype: HTMLWsTopDrawerElement;
        new (): HTMLWsTopDrawerElement;
    };
    interface HTMLWsWonkyDonkeyElement extends Components.WsWonkyDonkey, HTMLStencilElement {
    }
    var HTMLWsWonkyDonkeyElement: {
        prototype: HTMLWsWonkyDonkeyElement;
        new (): HTMLWsWonkyDonkeyElement;
    };
    interface HTMLElementTagNameMap {
        "ws-full-cover": HTMLWsFullCoverElement;
        "ws-hex-menu": HTMLWsHexMenuElement;
        "ws-side-buttons": HTMLWsSideButtonsElement;
        "ws-side-drawer": HTMLWsSideDrawerElement;
        "ws-top-drawer": HTMLWsTopDrawerElement;
        "ws-wonky-donkey": HTMLWsWonkyDonkeyElement;
    }
}
declare namespace LocalJSX {
    interface WsFullCover {
        "menuLink"?: any[];
        "opened"?: boolean;
    }
    interface WsHexMenu {
        "menuLink"?: any[];
        "onWsTileSelected"?: (event: CustomEvent<string>) => void;
        "opened"?: boolean;
    }
    interface WsSideButtons {
        "menuLink"?: any[];
    }
    interface WsSideDrawer {
        "opened"?: boolean;
        "titl"?: string;
    }
    interface WsTopDrawer {
        "menuLink"?: any[];
        "menuTitle"?: string;
        "opened"?: boolean;
    }
    interface WsWonkyDonkey {
        "menuLink"?: any[];
        "menuTitle"?: string;
        "opened"?: boolean;
    }
    interface IntrinsicElements {
        "ws-full-cover": WsFullCover;
        "ws-hex-menu": WsHexMenu;
        "ws-side-buttons": WsSideButtons;
        "ws-side-drawer": WsSideDrawer;
        "ws-top-drawer": WsTopDrawer;
        "ws-wonky-donkey": WsWonkyDonkey;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ws-full-cover": LocalJSX.WsFullCover & JSXBase.HTMLAttributes<HTMLWsFullCoverElement>;
            "ws-hex-menu": LocalJSX.WsHexMenu & JSXBase.HTMLAttributes<HTMLWsHexMenuElement>;
            "ws-side-buttons": LocalJSX.WsSideButtons & JSXBase.HTMLAttributes<HTMLWsSideButtonsElement>;
            "ws-side-drawer": LocalJSX.WsSideDrawer & JSXBase.HTMLAttributes<HTMLWsSideDrawerElement>;
            "ws-top-drawer": LocalJSX.WsTopDrawer & JSXBase.HTMLAttributes<HTMLWsTopDrawerElement>;
            "ws-wonky-donkey": LocalJSX.WsWonkyDonkey & JSXBase.HTMLAttributes<HTMLWsWonkyDonkeyElement>;
        }
    }
}
